from postgres:11
ENV POSTGRES_USER		postgres
ENV POSTGRES_PASSWORD	123456
run ["mkdir", "/opt/dev"]
COPY init.sql /docker-entrypoint-initdb.d/
RUN chmod a+r /docker-entrypoint-initdb.d/*
EXPOSE 5432

